name: Bug Minecraft
description: Bug with Minecraft report
title: '[Bug] '
assignees:
  - Chaika9
labels:
  - bug
  - Minecraft
body:
  - type: input
    id: minecraft-username
    attributes:
      label: Minecraft Username
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 'Description of the bug'
      description: 'Write a short description of the bug. You can write in French or English.'
    validations:
      required: true