name: Bug Report
description: Bug report
title: '[Bug] '
labels:
  - bug
body:
  - type: input
    id: minecraft-username
    attributes:
      label: Minecraft Username
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 'Description of the bug'
      description: 'Write a short description of the bug. You can write in French or English.'
    validations:
      required: true